# Generated by Django 5.1.1 on 2024-10-03 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MzuriFarmingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='PasswordHash',
            new_name='Password',
        ),
    ]
