# Generated by Django 5.1.1 on 2024-10-17 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MzuriFarmingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crops',
            old_name='crop_name',
            new_name='cropName',
        ),
        migrations.RenameField(
            model_name='crops',
            old_name='scientific_name',
            new_name='scientificName',
        ),
    ]
