# Generated by Django 5.1.1 on 2024-10-03 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MzuriFarmingApp', '0002_rename_passwordhash_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='CreatedAt',
        ),
        migrations.RemoveField(
            model_name='users',
            name='Role',
        ),
    ]
